
[general]
	#When the next EMC mapping occurs write the results to config/ProjectE/pregenerated_emc.json and only ever run the mapping again when that file does not exist, this setting is set to false, or an error occurred parsing that file.
	pregenerate = false
	#Want to take a look at the internals of EMC Calculation? Enable this to write all the conversions and setValue-Commands to config/ProjectE/mappingdump.json
	dumpEverythingToFile = false
	#Log known EMC Exploits. This can not and will not find all possible exploits. This will only find exploits that result in fixed/custom emc values that the algorithm did not overwrite. Exploits that derive from conversions that are unknown to ProjectE will not be found.
	logEMCExploits = true

[CraftingMapper]

	[CraftingMapper.BotaniaElvenTradeMapper]
		#ProjectE-Integration Recipe Mapper for Botania Elven Trade Mapper. Required Mods: [botania]
		enabled = true

	[CraftingMapper.MekPaintingMachine]
		#Maps Mekanism painting machine recipes.
		enabled = true

	[CraftingMapper.CreateDeployerApplicationMapper]
		#ProjectE-Integration Recipe Mapper for Create Deployer Application Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.AE2Charger]
		#(AppliedE) Maps Applied Energistics 2 charger recipes.
		enabled = true

	[CraftingMapper.CreateMillingMapper]
		#ProjectE-Integration Recipe Mapper for Create Milling Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.MekChemicalInfuser]
		#Maps Mekanism chemical infuser recipes.
		enabled = true

	[CraftingMapper.CreateBASINMapper]
		#ProjectE-Integration Recipe Mapper for Create BASINMapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.ExtendedCraftingTableMapper]
		#Maps Extended Crafting Table recipes
		enabled = true

	[CraftingMapper.ArsNouveauGlyphMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Glyph Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.MekChemicalCrystallizer]
		#Maps Mekanism crystallizing recipes.
		enabled = true

	[CraftingMapper.MekMetallurgicInfuser]
		#Maps Mekanism metallurgic infuser recipes.
		enabled = true

	[CraftingMapper.CreateSandpaperPolishingMapper]
		#ProjectE-Integration Recipe Mapper for Create Sandpaper Polishing Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateCompactingMapper]
		#ProjectE-Integration Recipe Mapper for Create Compacting Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.FallbackRecipeType]
		#Fallback for default handling of recipes that extend ICraftingRecipe, AbstractCookingRecipe, SingleItemRecipe, or SmithingRecipe. This will catch modded extensions of the vanilla recipe classes, and if the VanillaRecipeTypes mapper is disabled, this mapper will still catch the vanilla recipes.
		enabled = true

	[CraftingMapper.BotaniaManaInfusionMapper]
		#ProjectE-Integration Recipe Mapper for Botania Mana Infusion Mapper. Required Mods: [botania]
		enabled = true

	[CraftingMapper.VanillaRecipeTypes]
		#Maps the different vanilla recipe types.
		enabled = true

	[CraftingMapper.MysticalAgricultureReprocessorMapper]
		#ProjectE-Integration Recipe Mapper for Mystical Agriculture Reprocessor Mapper. Required Mods: [mysticalagriculture]
		enabled = true

	[CraftingMapper.MekRotary]
		#Maps Mekanism rotary condensentrator recipes.
		enabled = true

	[CraftingMapper.ExtendedCraftingCombinationMapper]
		#Maps Extended Crafting Combination recipes
		enabled = true

	[CraftingMapper.MekItemStackToPigment]
		#Maps Mekanism item stack to pigment recipes. (Pigment Extracting)
		enabled = true

	[CraftingMapper.MekItemStackGasToItemStack]
		#Maps Mekanism Machine recipes that go from item, gas to item. (Compressing, Purifying, Injecting)
		enabled = true

	[CraftingMapper.BotaniaRuneAlterMapper]
		#ProjectE-Integration Recipe Mapper for Botania Rune Alter Mapper. Required Mods: [botania]
		enabled = true

	[CraftingMapper.CreateHauntingMapper]
		#ProjectE-Integration Recipe Mapper for Create Haunting Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateMechanicalCraftingMapper]
		#ProjectE-Integration Recipe Mapper for Create Mechanical Crafting Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.BotaniaPetalMapper]
		#ProjectE-Integration Recipe Mapper for Botania Petal Mapper. Required Mods: [botania]
		enabled = true

	[CraftingMapper.CreatePressingMapper]
		#ProjectE-Integration Recipe Mapper for Create Pressing Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.MekPressurizedReaction]
		#Maps Mekanism pressurized reaction recipes.
		enabled = false

	[CraftingMapper.MekPigmentMixer]
		#Maps Mekanism pigment mixer recipes.
		enabled = true

	[CraftingMapper.MekItemStackToGas]
		#Maps Mekanism item stack to gas recipes. (Gas conversion, Oxidizing)
		enabled = true

	[CraftingMapper.ArsNouveauImbuementMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Imbuement Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.AE2Transform]
		#(AppliedE) Maps Applied Energistics 2 in-world transformation recipes.
		enabled = true

	[CraftingMapper.CreateItemApplicationMapper]
		#ProjectE-Integration Recipe Mapper for Create Item Application Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateSequencedAssemblyMapper]
		#ProjectE-Integration Recipe Mapper for Create Sequenced Assembly Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.MekElectrolysis]
		#Maps Mekanism electrolytic separator recipes.
		enabled = true

	[CraftingMapper.AE2Inscriber]
		#(AppliedE) Maps Applied Energistics 2 inscriber recipes.
		enabled = true

	[CraftingMapper.MekGasToGas]
		#Maps Mekanism activating and centrifuging recipes.
		enabled = true

	[CraftingMapper.MekItemStackToItemStack]
		#Maps Mekanism Machine recipes that go from item to item. (Crushing, Enriching, Smelting)
		enabled = true

	[CraftingMapper.MysticalAgricultureInfusionMapper]
		#ProjectE-Integration Recipe Mapper for Mystical Agriculture Infusion Mapper. Required Mods: [mysticalagriculture]
		enabled = true

	[CraftingMapper.BotaniaTerraPlateMapper]
		#ProjectE-Integration Recipe Mapper for Botania Terra Plate Mapper. Required Mods: [botania]
		enabled = true

	[CraftingMapper.CreateCUTTINGMapper]
		#ProjectE-Integration Recipe Mapper for Create CUTTINGMapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.MekSawmill]
		#Maps Mekanism sawmill recipes. (Disabled by default, due to causing various EMC values to be removed pertaining to charcoal/wood)
		enabled = false

	[CraftingMapper.ExtendedCraftingCompressorMapper]
		#ProjectE-Integration Recipe Mapper for Extended Crafting Compressor Mapper. Required Mods: [extendedcrafting]
		enabled = true

	[CraftingMapper.MekCombiner]
		#Maps Mekanism combiner recipes.
		enabled = true

	[CraftingMapper.BotaniaPureDaisyMapper]
		#ProjectE-Integration Recipe Mapper for Botania Pure Daisy Mapper. Required Mods: [botania]
		enabled = true

	[CraftingMapper.MekFluidToFluid]
		#Maps Mekanism evaporating recipes.
		enabled = true

	[CraftingMapper.Smithing]
		#Maps smithing recipes.
		enabled = true

	[CraftingMapper.CreateSplashingMapper]
		#ProjectE-Integration Recipe Mapper for Create Splashing Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.CreateCuttingMapper]
		#ProjectE-Integration Recipe Mapper for Create Cutting Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.MekItemStackToInfuseType]
		#Maps Mekanism item stack to infuse type conversion recipes.
		enabled = true

	[CraftingMapper.ArsNouveauCrushMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Crush Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.AppliedEnergisticsInscriberMapper]
		#ProjectE-Integration Recipe Mapper for Applied Energistics Inscriber Mapper. Required Mods: [ae2]
		enabled = true

	[CraftingMapper.MekDissolution]
		#Maps Mekanism dissolution recipes.
		enabled = true

	[CraftingMapper.MekFluidSlurryToSlurry]
		#Maps Mekanism washing recipes.
		enabled = true

	[CraftingMapper.ExtendedCraftingEnderCrafterMapper]
		#Maps extended crafting Ender Crafter recipes
		enabled = true

	[CraftingMapper.CreateCrushingMapper]
		#ProjectE-Integration Recipe Mapper for Create Crushing Mapper. Required Mods: [create]
		enabled = true

	[CraftingMapper.ArsNouveauEnchantingApparatusMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Enchanting Apparatus Mapper. Required Mods: [ars_nouveau]
		enabled = true

[permissions]

	[permissions.appliede]
		#Allow mod 'appliede' to set and or remove values for mod 'ae2'. Options: [both, set, remove, none]
		ae2 = "both"

[APICustomEMCMapper]

	[APICustomEMCMapper.priority]
		#Priority for this mod
		appliede = 1

[enabledMappers]
	#Set EMC=0 for everything in the forge:raw_materials tag
	RawOresBlacklistMapper = true
	#(AppliedE) Maps Applied Energistics 2 matter condenser results.
	AE2MatterCondenser = true
	#Add Conversions for Crafting Recipes gathered from net.minecraft.item.crafting.RecipeManager
	CraftingMapper = true
	#Adds back and forth conversions of objects and their Tag variant. (EMC values assigned to tags will not behave properly if this mapper is disabled)
	TagMapper = true
	#Add Conversions for Brewing Recipes
	BrewingMapper = true
	#Recipe mapper for custom recipes that don't implement IRecipe
	ProjectEIntegrationRecipeMapper = true
	#Loads json files within datapacks (data/<domain>/pe_custom_conversions/*.json) to add values and conversions
	CustomConversionMapper = true
	#Set EMC=0 for everything in the forge:ores tag
	OresBlacklistMapper = true
	#Add Conversions for all lingering potions to arrow recipes
	TippedArrowMapper = true
	#Add Conversions for all weathered copper variants
	WeatheredCopperMapper = true
	#(AppliedE) Maps Applied Energistics 2 cable facades.
	AE2FacadeMapper = true
	#Uses the `custom_emc.json` File to add EMC values.
	CustomEMCMapper = true
	#Allows other mods to easily set EMC values using the ProjectEAPI
	APICustomEMCMapper = true
	#(AppliedE) Maps Applied Energistics 2 P2P tunnels.
	AE2P2PTunnels = true

